sql_warehouse:
  - name: "DBT_DATTA_CLUSTER_EUH_warehouse"
    cluster_size: "Medium"
    warehouse_type: "PRO"
    enable_serverless_compute: true
    min_num_clusters: 1
    max_num_clusters: 4
    auto_stop_mins: 5
    tags:
      - key: "Name"
        value: "DBT_DATTA_CLUSTER_EUH_INIT_AND_DELTA"

  - name: "DBT_DATTA_COPA_EUH_D_BW_warehouse"
    cluster_size: "Small"
    warehouse_type: "PRO"
    enable_serverless_compute: true
    min_num_clusters: 1
    max_num_clusters: 4
    auto_stop_mins: 5
    tags:
      - key: "Name"
        value: "DBT_DATTA_COPA_EUH_D_BW"


  - name: "DBT_DATTA_FI_EH_D_warehouse"
    cluster_size: "X-Small"
    warehouse_type: "PRO"
    enable_serverless_compute: true
    min_num_clusters: 1
    max_num_clusters: 3
    auto_stop_mins: 5
    tags:
      - key: "Name"
        value: "DBT_DATTA_FI_EH_D"


  - name: "DBT_DATTA_FI_EUH_D_HANA_warehouse"
    cluster_size: "X-Small"
    warehouse_type: "PRO"
    enable_serverless_compute: true
    min_num_clusters: 1
    max_num_clusters: 3
    auto_stop_mins: 5
    tags:
      - key: "Name"
        value: "DBT_DATTA_FI_EUH_D_HANA"


  - name: "DBT_DATTA_FI_EUH_warehouse"
    cluster_size: "Medium"
    warehouse_type: "PRO"
    enable_serverless_compute: true
    min_num_clusters: 1
    max_num_clusters: 4
    auto_stop_mins: 5
    tags:
      - key: "Name"
        value: "DBT_DATTA_FI_EUH"


  - name: "DBT_DATTA_MD_ATTR_EUH_SD_D_HANA_warehouse"
    cluster_size: "X-Small"
    warehouse_type: "PRO"
    enable_serverless_compute: true
    min_num_clusters: 1
    max_num_clusters: 4
    auto_stop_mins: 5
    tags:
      - key: "Name"
        value: "DBT_DATTA_MD_ATTR_EUH_SD_D_HANA"

  - name: "DBT_DATTA_HM_EUH_D_warehouse"
    cluster_size: "X-Small"
    warehouse_type: "PRO"
    enable_serverless_compute: true
    min_num_clusters: 1
    max_num_clusters: 2
    auto_stop_mins: 5
    tags:
      - key: "Name"
        value: "DBT_DATTA_HM_EUH_D"

  - name: "DBT_DATTA_MD_ATTR_EUH_COPA_D_BW_warehouse"
    cluster_size: "X-Small"
    warehouse_type: "PRO"
    enable_serverless_compute: true
    min_num_clusters: 1
    max_num_clusters: 2
    auto_stop_mins: 5
    tags:
      - key: "Name"
        value: "DBT_DATTA_MD_ATTR_EUH_COPA_D_BW"


  - name: "DBT_DATTA_MD_ATTR_EUH_FI_D_HANA_warehouse"
    cluster_size: "X-Small"
    warehouse_type: "PRO"
    enable_serverless_compute: true
    min_num_clusters: 1
    max_num_clusters: 2
    auto_stop_mins: 5
    tags:
      - key: "Name"
        value: "DBT_DATTA_MD_ATTR_EUH_FI_D"

  - name: "DBT_DATTA_MD_EH_FI_D_warehouse"
    cluster_size: "X-Small"
    warehouse_type: "PRO"
    enable_serverless_compute: true
    min_num_clusters: 1
    max_num_clusters: 2
    auto_stop_mins: 5
    tags:
      - key: "Name"
        value: "DBT_DATTA_MD_EH_FI_D"

  - name: "DBT_DATTA_MD_EH_SD_D_HANA"
    cluster_size: "X-Small"
    warehouse_type: "PRO"
    enable_serverless_compute: true
    min_num_clusters: 1
    max_num_clusters: 2
    auto_stop_mins: 5
    tags:
      - key: "Name"
        value: "DBT_DATTA_MD_EH_SD_D"

  - name: "DBT_DATTA_SD_EUH_D"
    cluster_size: "X-Small"
    warehouse_type: "PRO"
    enable_serverless_compute: true
    min_num_clusters: 1
    max_num_clusters: 2
    auto_stop_mins: 5
    tags:
      - key: "Name"
        value: "DBT_DATTA_SD_EUH_D"
