{{
  config(
    materialized = 'incremental',
    unique_key=['Source_ID','Company_Code','Accounting_Document_Number','Fiscal_Year','Number_Of_Line_Item_Within_Accounting_Document'],
    on_schema_change = 'ignore',
    tags=["FI-EH-D"]
    )
}}

with rename_filter_bkpf_stn as (
  Select
  MANDT AS Client,
  BUKRS AS Company_Code,
  BELNR AS Accounting_Document_Number,
  GJAHR AS Fiscal_Year,
  BLART AS Document_Type,
  BLDAT AS Document_Date_In_Document,
  BUDAT AS Posting_Date_In_The_Document,
  MONAT AS Fiscal_Period,
  CPUDT AS Day_On_Which_Accounting_Document_Was_Entered,
  CPUTM AS Time_Of_Entry,
  AEDAT AS Date_Of_The_Last_Document_Change_By_Transaction,
  UPDDT AS Date_Of_The_Last_Document_Update,
  WWERT AS Translation_Date,
  USNAM AS User_Name,
  TCODE AS Transaction_Code,
  BVORG AS Number_Of_Cross_Company_Code_Posting_Transaction,
  XBLNR AS Reference_Document_Number,
  DBBLG AS Recurring_Entry_Document_Number,
  STBLG AS Reverse_Document_Number,
  STJAH AS Reverse_Document_Fiscal_Year,
  BKTXT AS Document_Header_Text,
  WAERS AS Currency_Key,
  KURSF AS Exchange_Rate,
  KZWRS AS Currency_Key_For_The_Group_Currency,
  KZKRS AS Group_Currency_Exchange_Rate,
  BSTAT AS Document_Status,
  XNETB AS Indicator_Document_Posted_Net,
  FRATH AS Unplanned_Delivery_Costs,
  XRUEB AS Indicator_Document_Is_Posted_To_A_Previous_Period,
  GLVOR AS Business_Transaction,
  GRPID AS Batch_Input_Session_Name,
  DOKID AS Document_Name_In_The_Archive_System,
  ARCID AS Extract_Id_Document_Header,
  IBLAR AS Internal_Document_Type_For_Document_Control,
  AWTYP AS Reference_Procedure,
  AWKEY AS Object_Key,
  FIKRS AS Financial_Management_Area,
  HWAER AS Local_Currency,
  HWAE2 AS Currency_Key_Of_Second_Local_Currency,
  HWAE3 AS Currency_Key_Of_Third_Local_Currency,
  KURS2 AS Exchange_Rate_For_The_Second_Local_Currency,
  KURS3 AS Exchange_Rate_For_The_Third_Local_Currency,
  BASW2 AS Source_Currency_For_Currency_Translation_2,
  BASW3 AS Source_Currency_For_Currency_Translation_3,
  UMRD2 AS Translation_Date_Type_For_Second_Local_Currency,
  UMRD3 AS Translation_Date_Type_For_Third_Local_Currency,
  XSTOV AS Indicator_Document_Is_Flagged_For_Reversal,
  STODT AS Planned_Date_For_The_Reverse_Posting,
  XMWST AS Calculate_Tax_Automatically,
  CURT2 AS Currency_Type_Of_Second_Local_Currency,
  CURT3 AS Currency_Type_Of_Third_Local_Currency,
  KUTY2 AS Exchange_Rate_Type_2,
  KUTY3 AS Exchange_Rate_Type_3,
  XSNET AS GL_Account_Amounts_Entered_Exclude_Tax,
  AUSBK AS Source_Company_Code,
  XUSVR AS Enter_Vat_Use_Tax_Sales_Tax_On_Detail_Screen,
  DUEFL AS Status_Of_Data_Transfer_Into_Subsequent_Release,
  AWSYS AS Logical_System,
  TXKRS AS Exchange_Rate_For_Taxes,
  CTXKRS AS Rate_For_Tax_Values_In_Local_Currency,
  LOTKZ AS Lot_Number_For_Requests,
  XWVOF AS Indicator_Customer_Bill_Of_Exchange_Payment_Before_Due_Date,
  STGRD AS Reason_For_Reversal_Or_Inverse_Posting,
  PPNAM AS Name_Of_User_Who_Parked_This_Document,
  PPDAT AS Day_Of_Parking_Of_Accounting_Document,
  PPTME AS Time_Of_Parking,
  PPTCOD AS Parking_Transaction,
  BRNCH AS Branch_Number,
  NUMPG AS Number_Of_Pages_Of_Invoice,
  ADISC AS Indicator_Entry_Represents_A_Discount_Document,
  XREF1_HD AS Reference_Key_1_Internal_For_Document_Header,
  XREF2_HD AS Reference_Key_2_Internal_For_Document_Header,
  XREVERSAL AS Specifies_Whether_Doc_Is_Reversal_Doc_Or_Reversed_Doc,
  REINDAT AS Invoice_Receipt_Date,
  RLDNR AS Ledger_In_General_Ledger_Accounting,
  LDGRP AS Ledger_Group,
  PROPMANO AS Real_Estate_Management_Mandate,
  XBLNR_ALT AS Alternative_Reference_Number,
  VATDATE AS Tax_Reporting_Date,
  DOCCAT AS Classification_Of_An_Fi_Document,
  XSPLIT AS Fi_Document_Originates_From_Split_Posting_Indicator,
  CASH_ALLOC AS Cash_Relevant_Document,
  FOLLOW_ON AS Follow_On_Document_Indicator,
  XREORG AS Doc_Contains_Open_Item_That_Was_Transferred_During_Reorg,
  SUBSET AS Defines_Subset_Of_Components_For_The_FiCo_Interface,
  KURST AS Exchange_Rate_Type,
  KURSX AS Market_Data_Exchange_Rate,
  KUR2X AS Market_Data_Exchange_Rate_2,
  KUR3X AS Market_Data_Exchange_Rate_3,
  XMCA AS Document_Originates_From_Multi_Currency_Accounting,
  RESUBMISSION AS Date_Of_Resubmission,
  `/SAPF15/STATUS` AS Document_Status_1,
  PSOTY AS Document_Category_Payment_Requests,
  PSOAK AS Reason,
  PSOKS AS Region,
  PSOSG AS Reason_For_Reversal_Is_Ps_Requests,
  PSOFN AS Is_Ps_File_Number,
  INTFORM AS Interest_Formula,
  INTDATE AS Interest_Calc_Date,
  PSOBT AS Posting_Day,
  PSOZL AS Actual_Posting,
  PSODT AS Date_Of_Last_Change,
  PSOTM AS Last_Changed_At,
  FM_UMART AS Type_Of_Payment_Transfer,
  CCINS AS Payment_Cards_Card_Type,
  CCNUM AS Payment_Cards_Card_Number,
  SSBLK AS Payment_Statistical_Sampling_Block,
  BATCH AS Lot_Number_For_Documents,
  SNAME AS User_Name_1,
  SAMPLED AS Sampled_Invoice_By_Payment_Certification,
  EXCLUDE_FLAG AS Ppa_Exclude_Indicator_BKPF,
  BLIND AS Budgetary_Ledger_Indicator,
  OFFSET_STATUS AS Treasury_Offset_Status,
  OFFSET_REFER_DAT AS Date_Record_Referred_To_Treasury,
  PENRC AS Reason_For_Late_Payment_BKPF,
  KNUMV AS Number_Of_The_Document_Condition,
  PYBASTYP AS Type_Of_Payment_Basis_Document_BKPF,
  PYBASNO AS Payment_Basis_Document_Number_BKPF,
  PYBASDAT AS Payment_Basis_Document_Date_BKPF,
  PYIBAN AS Iban_International_Bank_Account_Number,
  INWARDNO_HD AS Incoming_Document_Number_BKPF,
  INWARDDT_HD AS Incoming_Document_Date_BKPF,
  LAST_DTM AS LAST_DTM,
  ingested_at AS ingested_at
  from {{ref('BKPF_STN')}}
  where MANDT = '280'

),
rename_filter_bseg_stn as(
  Select
  MANDT AS Client ,
   BUZEI AS Number_Of_Line_Item_Within_Accounting_Document ,
   BUZID AS Identification_Of_The_Line_Item ,
   AUGDT AS Clearing_Date ,
   AUGCP AS Clearing_Entry_Date ,
   AUGBL AS Document_Number_Of_The_Clearing_Document ,
   BSCHL AS Posting_Key ,
   KOART AS Account_Type ,
   UMSKZ AS Special_GL_Indicator ,
   UMSKS AS Special_GL_Transaction_Type ,
   ZUMSK AS Target_Special_GL_Indicator ,
   SHKZG AS Debit_Credit_Indicator ,
   GSBER AS Business_Area ,
   PARGB AS Trading_PartnerS_Business_Area ,
   MWSKZ AS Tax_On_Sales_Purchases_Code ,
   QSSKZ AS Withholding_Tax_Code ,
   DMBTR AS Amount_In_Local_Currency ,
   WRBTR AS Amount_In_Document_Currency ,
   KZBTR AS Original_Reduction_Amount_In_Local_Currency ,
   PSWBT AS Amount_For_Updating_In_General_Ledger ,
   PSWSL AS Update_Currency_For_General_Ledger_Transaction_Figures ,
   TXBHW AS Original_Tax_Base_Amount_In_Local_Currency ,
   TXBFW AS Original_Tax_Base_Amount_In_Document_Currency ,
   MWSTS AS Tax_Amount_In_Local_Currency ,
   WMWST AS Tax_Amount_In_Document_Currency ,
   HWBAS AS Tax_Base_Amount_In_Local_Currency ,
   FWBAS AS Tax_Base_Amount_In_Document_Currency ,
   HWZUZ AS Provision_Amount_In_Local_Currency ,
   FWZUZ AS Additional_Tax_In_Document_Currency ,
   SHZUZ AS DebitCredit_Addition_For_Cash_Discount ,
   STEKZ AS Version_Number_Component ,
   MWART AS Tax_Type ,
   TXGRP AS Group_Indicator_For_Tax_Line_Items ,
   KTOSL AS Transaction_Key ,
   QSSHB AS Withholding_Tax_Base_Amount ,
   KURSR AS Hedged_Exchange_Rate ,
   GBETR AS Hedged_Amount_In_Foreign_Currency ,
   BDIFF AS Valuation_Difference ,
   BDIF2 AS Valuation_Difference_For_The_Second_Local_Currency ,
   VALUT AS Value_Date ,
   ZUONR AS Assignment_Number ,
   SGTXT AS Item_Text ,
   ZINKZ AS Exempted_From_Interest_Calculation ,
   VBUND AS Company_Id_Of_Trading_Partner ,
   BEWAR AS Transaction_Type ,
   ALTKT AS Group_Account_Number ,
   VORGN AS Transaction_Type_For_General_Ledger ,
   FDLEV AS Planning_Level ,
   FDGRP AS Planning_Group ,
   FDWBT AS Planned_Amount_In_Document_Or_GL_Account_Currency ,
   FDTAG AS Planning_Date ,
   FKONT AS Financial_Budget_Item ,
   KOKRS AS Controlling_Area ,
   KOSTL AS Cost_Center ,
   PROJN AS Old_Project_Number_No_Longer_Used_PsPosnr ,
   AUFNR AS Order_Number ,
   VBELN AS Billing_Document ,
   VBEL2 AS Sales_Document ,
   POSN2 AS Sales_Document_Item ,
   ETEN2 AS Schedule_Line_Number ,
   ANLN1 AS Main_Asset_Number ,
   ANLN2 AS Asset_Subnumber ,
   ANBWA AS Asset_Transaction_Type ,
   BZDAT AS Asset_Value_Date ,
   PERNR AS Personnel_Number ,
   XUMSW AS Indicator_Sales_Related_Item ,
   XHRES AS Indicator_Resident_GL_Account ,
   XKRES AS Indicator_Can_Line_Items_Be_Displayed_By_Account ,
   XOPVW AS Indicator_Open_Item_Management ,
   XCPDD AS Indicator_Address_And_Bank_Data_Set_Individually ,
   XSKST AS Indicator_Statistical_Posting_To_Cost_Center ,
   XSAUF AS Indicator_Posting_To_Order_Is_Statistical ,
   XSPRO AS Indicator_Posting_To_Project_Is_Statistical ,
   XSERG AS Indicator_Posting_To_Profitability_Analysis_Is_Statistical ,
   XFAKT AS Indicator_Billing_Document_Update_Successful ,
   XUMAN AS Indicator_Transfer_Posting_From_Down_Payment ,
   XANET AS Indicator_Down_Payment_In_Net_Procedure ,
   XSKRL AS Indicator_Line_Item_Not_Liable_To_Cash_Discount ,
   XINVE AS Indicator_Capital_Goods_Affected ,
   XPANZ AS Display_Item ,
   XAUTO AS Indicator_Line_Item_Automatically_Created ,
   XNCOP AS Indicator_Items_Cannot_Be_Copied ,
   XZAHL AS Indicator_Is_Posting_Key_Used_In_A_Payment_Transaction ,
   SAKNR AS GL_Account_Number ,
   HKONT AS General_Ledger_Account ,
   KUNNR AS Customer_Number ,
   LIFNR AS Account_Number_Of_Supplier ,
   FILKD AS Account_Number_Of_The_Branch ,
   XBILK AS Indicator_Account_Is_A_Balance_Sheet_Account ,
   GVTYP AS PL_Statement_Account_Type ,
   HZUON AS Assignment_Number_For_Special_GL_Accounts ,
   ZFBDT AS Baseline_Date_For_Due_Date_Calculation ,
   ZTERM AS Terms_Of_Payment_Key ,
   ZBD1T AS Cash_Discount_Days_1 ,
   ZBD2T AS Cash_Discount_Days_2 ,
   ZBD3T AS Net_Payment_Terms_Period ,
   ZBD1P AS Cash_Discount_Percentage_1 ,
   ZBD2P AS Cash_Discount_Percentage_2 ,
   SKFBT AS Amount_Eligible_For_Cash_Discount_In_Document_Currency ,
   SKNTO AS Cash_Discount_Amount_In_Local_Currency ,
   WSKTO AS Cash_Discount_Amount_In_Document_Currency ,
   ZLSCH AS Payment_Method ,
   ZLSPR AS Payment_Block_Key ,
   ZBFIX AS Fixed_Payment_Terms ,
   HBKID AS Short_Key_For_A_House_Bank ,
   BVTYP AS Partner_Bank_Type ,
   NEBTR AS Net_Payment_Amount ,
   MWSK1 AS Tax_Code_For_Distribution_1 ,
   DMBT1 AS Amount_In_Local_Currency_For_Tax_Distribution_1 ,
   WRBT1 AS Amount_In_Foreign_Currency_For_Tax_Breakdown_1 ,
   MWSK2 AS Tax_Code_For_Distribution_2 ,
   DMBT2 AS Amount_In_Local_Currency_For_Tax_Distribution_2 ,
   WRBT2 AS Amount_In_Foreign_Currency_For_Tax_Breakdown_2 ,
   MWSK3 AS Tax_Code_For_Distribution_3 ,
   DMBT3 AS Amount_In_Local_Currency_For_Tax_Distribution_3 ,
   WRBT3 AS Amount_In_Foreign_Currency_For_Tax_Breakdown_3 ,
   REBZG AS Document_No_Of_The_Invoice_To_Which_The_Transaction_Belongs ,
   REBZJ AS Fiscal_Year_Of_The_Relevant_Invoice_For_Credit_Memo ,
   REBZZ AS Line_Item_In_The_Relevant_Invoice ,
   REBZT AS Follow_On_Document_Type ,
   ZOLLT AS Customs_Tariff_Number ,
   ZOLLD AS Customs_Date ,
   LZBKZ AS State_Central_Bank_Indicator ,
   LANDL AS Supplying_Country ,
   DIEKZ AS Service_Indicator_Foreign_Payment ,
   SAMNR AS Invoice_List_Number ,
   ABPER AS Settlement_Period ,
   VRSKZ AS Insurance_Indicator ,
   VRSDT AS Insurance_Date ,
   DISBN AS Number_Of_Bill_Of_Exchange_Usage_Document_Discount_Doc ,
   DISBJ AS Fiscal_Year_Of_Bill_Of_Exchange_Usage_Document ,
   DISBZ AS Line_Item_Within_The_Bill_Of_Exchange_Usage_Document ,
   WVERW AS Bill_Of_Exchange_Usage_Type ,
   ANFBN AS Document_Number_Of_The_Bill_Of_Exchange_Payment_Request ,
   ANFBJ AS Fiscal_Year_Of_The_Bill_Of_Exchange_Payment_Request_Document ,
   ANFBU AS Company_Code_In_Which_Bill_Of_ExchPayment_Request_Is_Posted ,
   ANFAE AS Bill_Of_Exchange_Payment_Request_Due_Date ,
   BLNBT AS Base_Amount_For_Determining_The_Preference_Amount ,
   BLNKZ AS Subsidy_Indicator_For_Determining_The_Reduction_Rates ,
   BLNPZ AS Preference_Percentage_Rate ,
   MSCHL AS Dunning_Key ,
   MANSP AS Dunning_Block ,
   MADAT AS Date_Of_Last_Dunning_Notice ,
   MANST AS Dunning_Level ,
   MABER AS Dunning_Area ,
   ESRNR AS Isr_Subscriber_Number ,
   ESRRE AS IsrQr_Reference_Number ,
   ESRPZ AS Por_Check_Digit ,
   KLIBT AS Credit_Control_Amount ,
   QSZNR AS Certificate_Number_Of_The_Withholding_Tax_Exemption ,
   QBSHB AS Withholding_Tax_Amount_In_Document_Currency ,
   QSFBT AS Withholding_Tax_Exempt_Amount_In_Document_Currency ,
   NAVHW AS Non_Deductible_Input_Tax_In_Local_Currency ,
   NAVFW AS Non_Deductible_Input_Tax_In_Document_Currency ,
   MATNR AS Material_Number ,
   WERKS AS Plant ,
   MENGE AS Quantity ,
   MEINS AS Base_Unit_Of_Measure ,
   ERFMG AS Quantity_In_Unit_Of_Entry ,
   ERFME AS Unit_Of_Entry ,
   BPMNG AS Quantity_In_Purchase_Order_Price_Unit ,
   BPRME AS Order_Price_Unit_Purchasing ,
   EBELN AS Purchasing_Document_Number ,
   EBELP AS Item_Number_Of_Purchasing_Document ,
   ZEKKN AS Sequential_Number_Of_Account_Assignment ,
   ELIKZ AS Delivery_Completed_Indicator ,
   VPRSV AS Price_Control_Indicator ,
   PEINH AS Price_Unit ,
   BWKEY AS Valuation_Area ,
   BWTAR AS Valuation_Type ,
   BUSTW AS Posting_String_For_Values ,
   REWRT AS Invoice_Value_Entered_In_Local_Currency ,
   REWWR AS Invoice_Value_In_Foreign_Currency ,
   BONFB AS Amount_Qualifying_For_Bonus_In_Local_Currency ,
   BUALT AS Amount_Posted_In_Alternative_Price_Control ,
   PSALT AS Alternative_Price_Control ,
   NPREI AS New_Price ,
   TBTKZ AS Indicator_Subsequent_DebitCredit ,
   SPGRP AS Blocking_Reason_Price ,
   SPGRM AS Blocking_Reason_Quantity ,
   SPGRT AS Blocking_Reason_Date ,
   SPGRG AS Blocking_Reason_Order_Price_Quantity ,
   SPGRV AS Blocking_Reason_Project_Budget ,
   SPGRQ AS Manual_Blocking_Reason ,
   STCEG AS Vat_Registration_Number ,
   EGBLD AS Country_Of_Destination_For_Delivery_Of_Goods ,
   EGLLD AS Supplying_Country_For_Delivery_Of_Goods ,
   RSTGR AS Reason_Code_For_Payments ,
   RYACQ AS Year_Of_Acquisition ,
   RPACQ AS Period_Of_Acquisition ,
   RDIFF AS Exchange_Rate_GainLoss_Realized ,
   RDIF2 AS Exchange_Rate_Difference_Realized_For_Second_Local_Currency ,
   PRCTR AS Profit_Center ,
   XHKOM AS Indicator_GL_Account_Assigned_Manually ,
   VNAME AS Joint_Venture ,
   RECID AS Recovery_Indicator ,
   EGRUP AS Equity_Group ,
   VPTNR AS Partner_Account_Number ,
   VERTT AS Contract_Type ,
   VERTN AS Contract_Number ,
   VBEWA AS Flow_Type ,
   DEPOT AS Securities_Account ,
   TXJCD AS Tax_Jurisdiction ,
   IMKEY AS Internal_Key_For_Real_Estate_Object ,
   DABRZ AS Reference_Date_For_Settlement ,
   POPTS AS Real_Estate_Option_Rate ,
   FIPOS AS Commitment_Item ,
   KSTRG AS Cost_Object ,
   NPLNR AS Network_Number_For_Account_Assignment ,
   AUFPL AS Task_List_Number_For_Operations_In_Order ,
   APLZL AS General_Counter_For_Order ,
   PROJK AS Work_Breakdown_Structure_Element_Wbs_Element ,
   PAOBJNR AS Profitability_Segment_Number_Co_Pa ,
   PASUBNR AS Profitability_Segment_Changes_Co_Pa ,
   SPGRS AS Blocking_Reason_Item_Amount ,
   SPGRC AS Blocking_Reason_Quality ,
   BTYPE AS Payroll_Type ,
   ETYPE AS Equity_Type ,
   XEGDR AS Indicator_Triangular_Deal_Within_The_Eu ,
   LNRAN AS Sequence_Number_Of_Asset_Line_Items_In_Fiscal_Year ,
   HRKFT AS Origin_Group_As_Subdivision_Of_Cost_Element ,
   DMBE2 AS Amount_In_Second_Local_Currency ,
   DMBE3 AS Amount_In_Third_Local_Currency ,
   DMB21 AS Amount_In_Second_Local_Currency_For_Tax_Breakdown_21 ,
   DMB22 AS Amount_In_Second_Local_Currency_For_Tax_Breakdown_22 ,
   DMB23 AS Amount_In_Second_Local_Currency_For_Tax_Breakdown_23 ,
   DMB31 AS Amount_In_Third_Local_Currency_For_Tax_Breakdown_31 ,
   DMB32 AS Amount_In_Third_Local_Currency_For_Tax_Breakdown_32 ,
   DMB33 AS Amount_In_Third_Local_Currency_For_Tax_Breakdown_33 ,
   MWST2 AS Tax_Amount_In_Second_Local_Currency ,
   MWST3 AS Tax_Amount_In_Third_Local_Currency ,
   NAVH2 AS Non_Deductible_Input_Tax_In_Second_Local_Currency ,
   NAVH3 AS Non_Deductible_Input_Tax_In_Third_Local_Currency ,
   SKNT2 AS Cash_Discount_Amount_In_Second_Local_Currency ,
   SKNT3 AS Cash_Discount_Amount_In_Third_Local_Currency ,
   BDIF3 AS Valuation_Difference_For_The_Third_Local_Currency ,
   RDIF3 AS Exchange_Rate_Difference_Realized_For_Third_Local_Currency ,
   HWMET AS Method_With_Which_The_Local_Currency_Amount_Was_Determined ,
   GLUPM AS Update_Method_For_Fm_Fi_Ca_Integration ,
   XRAGL AS Indicator_Clearing_Was_Reversed ,
   UZAWE AS Payment_Method_Supplement ,
   LOKKT AS Alternative_Account_Number_In_Company_Code ,
   FISTL AS Funds_Center ,
   GEBER AS Fund ,
   STBUK AS Tax_Company_Code ,
   TXBH2 AS Tax_BaseOriginal_Tax_Base_In_Second_Local_Currency ,
   TXBH3 AS Tax_BaseOriginal_Tax_Base_In_Third_Local_Currency ,
   PPRCT AS Partner_Profit_Center ,
   XREF1 AS Business_Partner_Reference_Key_1 ,
   XREF2 AS Business_Partner_Reference_Key_2 ,
   KBLNR AS Document_Number_For_Earmarked_Funds ,
   KBLPOS AS Earmarked_Funds_Document_Item ,
   STTAX AS Tax_Amount_As_Statistical_Information_In_Document_Currency ,
   FKBER AS Functional_Area ,
   OBZEI AS Number_Of_Line_Item_In_Original_Document ,
   XNEGP AS Indicator_Negative_Posting ,
   RFZEI AS Payment_Card_Item ,
   CCBTC AS Payment_Cards_Settlement_Run ,
   KKBER AS Credit_Control_Area ,
   EMPFB AS PayeePayer ,
   XREF3 AS Reference_Key_For_Line_Item ,
   DTWS1 AS Instruction_1 ,
   DTWS2 AS Instruction_2 ,
   DTWS3 AS Instruction_3 ,
   DTWS4 AS Instruction_4 ,
   GRICD AS Activity_Code_For_Gross_Income_Tax ,
   GRIRG AS Region_State_Province_County ,
   GITYP AS Distribution_Type_For_Employment_Tax ,
   XPYPR AS Indicator_Items_From_Payment_Program_Blocked ,
   KIDNO AS Payment_Reference ,
   ABSBT AS Credit_Management_Hedged_Amount ,
   IDXSP AS Inflation_Index ,
   LINFV AS Last_Adjustment_Date ,
   KONTT AS Account_Assignment_Category_For_Industry_Solution ,
   KONTL AS Acct_Assignment_String_For_Industry_Specific_Acct_Assignmnts ,
   TXDAT AS Date_For_Defining_Tax_Rates ,
   AGZEI AS Clearing_Item ,
   PYCUR AS Currency_For_Automatic_Payment ,
   PYAMT AS Amount_In_Payment_Currency ,
   BUPLA AS Business_Place ,
   SECCO AS Section_Code ,
   LSTAR AS Activity_Type ,
   CESSION_KZ AS Accounts_Receivable_Pledging_Indicator ,
   PRZNR AS Business_Process ,
   PPDIFF AS Realized_Exchange_Rate_GainLoss_1LocCurrPart_Payments ,
   PPDIF2 AS Realized_Exchange_Rate_GainLoss_2Loc_CurrPart_Payments ,
   PPDIF3 AS Realized_Exchange_Rate_GainLoss_3LocCurrPart_Payments ,
   PENLC1 AS Penalty_Charge_Amount_In_First_Local_Currency ,
   PENLC2 AS Penalty_Charge_Amount_In_Second_Local_Currency ,
   PENLC3 AS Penalty_Charge_Amount_In_Third_Local_Currency ,
   PENFC AS Penalty_Charge_Amount_In_Document_Currency ,
   PENDAYS AS Number_Of_Days_For_Penalty_Charge_Calculation ,
   PENRC AS Reason_For_Late_Payment_BSEG ,
   GRANT_NBR AS Grant ,
   SCTAX AS Tax_Portion_Fi_Ca_Local_Currency ,
   FKBER_LONG AS Functional_Area_Long ,
   GMVKZ AS Item_Is_In_Execution ,
   SRTYPE AS Type_Of_Additional_Receivable ,
   INTRENO AS Internal_Real_Estate_Master_Data_Code ,
   MEASURE AS Funded_Program ,
   AUGGJ AS Fiscal_Year_Of_Clearing_Document ,
   PPA_EX_IND AS Ppa_Exclude_Indicator_BSEG ,
   DOCLN AS Six_Character_Posting_Item_For_Ledger ,
   SEGMENT AS Segment_For_Segmental_Reporting ,
   PSEGMENT AS Partner_Segment_For_Segmental_Reporting ,
   PFKBER AS Partner_Functional_Area ,
   HKTID AS Id_For_Account_Details ,
   KSTAR AS Cost_Element ,
   XLGCLR AS Clearing_Specific_To_Ledger_Groups ,
   TAXPS AS Tax_Document_Item_Number ,
   PAYS_PROV AS Payment_Service_Provider ,
   PAYS_TRAN AS Payment_Reference_Of_Payment_Service_Provider ,
   MNDID AS Unique_Reference_To_Mandate_For_Each_Payee ,
   XFRGE_BSEG AS Payment_Is_Released ,
   SQUAN AS Quantity_Sign ,
   ACROBJTYPE AS Type_Of_The_Accrual_Object ,
   ACROBJ_ID AS Identifier_Of_The_Accrual_Object ,
   ACRSOBJ_ID AS Identifier_Of_The_Accrual_Sub_Object ,
   ACRITMTYPE AS Type_Of_The_Item_Of_The_Accrual_Sub_Object ,
   VALOBJTYPE AS Type_Of_The_Financial_Valuation_Object ,
   VALOBJ_ID AS Identifier_Of_The_Financial_Valuation_Object ,
   VALSOBJ_ID AS Identifier_Of_The_Financial_Valuation_Subobject ,
   RE_BUKRS AS Cash_Ledger_Company_Code_For_ExpenseRevenue ,
   RE_ACCOUNT AS Cash_Ledger_Expense_Or_Revenue_Account ,
   PGEBER AS Partner_Fund ,
   PGRANT_NBR AS Partner_Grant ,
   BUDGET_PD AS Fm_Budget_Period ,
   PBUDGET_PD AS Fm_Partner_Budget_Period ,
   J_1TPBUPL AS Branch_Code ,
   PEROP_BEG AS Billing_Period_Of_Performance_Start_Date ,
   PEROP_END AS Billing_Period_Of_Performance_End_Date ,
   FASTPAY AS Ppa_Fast_Pay_Indicator ,
   IGNR_IVREF AS Fmfg_Ignore_The_Invoice_Reference_During_Fi_Doc_Splitting ,
   FMFGUS_KEY AS United_States_Federal_Government_Fields ,
   FMXDOCNR AS Fm_Reference_Document_Number ,
   FMXYEAR AS Fm_Reference_Year ,
   FMXDOCLN AS Fm_Reference_Line_Item ,
   FMXZEKKN AS Fm_Reference_Sequence_Account_Assignment ,
   PRODPER AS Production_Month_Date_To_Find_Period_And_Year ,
   GST_PART AS Gst_Partner ,
   PLC_SUP AS Place_Of_Supply ,
   HSN_SAC AS Hsn_Or_Sac_Code ,
   IRN AS Invoice_Reference_Number ,
   RECRF AS Service_Tax_Recredit_Flag ,
   INWARD_NO AS Incoming_Document_Number_BSEG ,
   INWARD_DT AS Incoming_Document_Date_BSEG ,
   GROUND_NO AS Payment_Basis_Document_Number_BSEG ,
   GROUND_DT AS Payment_Basis_Document_Date_BSEG ,
   GROUND_TYP AS Type_Of_Payment_Basis_Document_BSEG ,
   PYMTKEY AS Payment_Or_Proposal_Key ,
   LAST_DTM AS LAST_DTM ,
   ingested_at AS ingested_at ,
   BUKRS AS Company_Code ,
   BELNR AS Accounting_Document_Number ,
   GJAHR AS Fiscal_Year
  from {{ref('BSEG_STN')}}
  where MANDT = '280'
),
bkpf_stn_delta as (
    select Company_Code,Accounting_Document_Number,Fiscal_Year
    from rename_filter_bkpf_stn
    {% if is_incremental() %}
     where ingested_at > (select max(Ingested_at) from {{this}})
    {% endif %}
),
bseg_stn_delta as (
    select Company_Code,Accounting_Document_Number,Fiscal_Year
    from rename_filter_bseg_stn
    {% if is_incremental() %}
     where ingested_at > (select max(Ingested_At) from {{this}})
   {% endif %}
),
bkpf_bseg_stn_pk as(
    select * from bkpf_stn_delta
    union
    select * from bseg_stn_delta
),
bkpf_stn_full as (
    select rename_filter_bkpf_stn.* except (ingested_at)
    from rename_filter_bkpf_stn
    inner join bkpf_bseg_stn_pk
    on rename_filter_bkpf_stn.Company_Code = bkpf_bseg_stn_pk.Company_Code
    and rename_filter_bkpf_stn.Accounting_Document_Number = bkpf_bseg_stn_pk.Accounting_Document_Number
    and rename_filter_bkpf_stn.Fiscal_Year = bkpf_bseg_stn_pk.Fiscal_Year

),
bkpf_bseg_stn as(
    select bkpf_stn_full.* , rename_filter_bseg_stn.* except (Client,Company_Code,Fiscal_Year,Accounting_Document_Number,LAST_DTM,ingested_at)
    from bkpf_stn_full
    left join rename_filter_bseg_stn
    on bkpf_stn_full.Company_Code = rename_filter_bseg_stn.Company_Code
    and bkpf_stn_full.Accounting_Document_Number = rename_filter_bseg_stn.Accounting_Document_Number
    and bkpf_stn_full.Fiscal_Year = rename_filter_bseg_stn.Fiscal_Year
)

select bkpf_bseg_stn.* except (Client),
current_timestamp() as Ingested_At,
('{{ set_system_id() }}' || "_" || bkpf_bseg_stn.Client) as Source_ID
from bkpf_bseg_stn
