{{
    config(
        materialized='table',
        on_schema_change='ignore',
    tags=["MD-EH-FI-D"]
    )
}}

with
rename_filter_t001_stn as (
    select
    MANDT AS  Client,
    BUKRS AS  Company_Code,
    BUTXT AS  Name_Of_Company_Code_Or_Company,
    ORT01 AS  City,
    LAND1 AS  Country_Key,
    WAERS AS  Currency_Key,
    SPRAS AS  Language_Key,
    KTOPL AS  Chart_Of_Accounts,
    WAABW AS  Maximum_Exchange_Rate_Deviation_In_Percent,
    PERIV AS  Fiscal_Year_Variant,
    KOKFI AS  Allocation_Indicator,
    RCOMP AS  Company,
    ADRNR AS  Address,
    STCEG AS  Vat_Registration_Number,
    FIKRS AS  Financial_Management_Area,
    XFMCO AS  Indicator_Project_Cash_Management_Active,
    XFMCB AS  Indicator_Cash_Budget_Management_Active,
    XFMCA AS  Activate_Update_In_Funds_Management,
    TXJCD AS  Jurisdiction_For_Tax_Calculation_Tax_Jurisdiction_Code,
    FMHRDATE AS  Funds_Center_Can_Be_Assigned_To_An_Account_In_Hr_From,
    BUVAR AS  Company_Code_Variant_Screen,
    FDBUK AS  Cash_Management_And_Forecast_Company_Code,
    XFDIS AS  Indicator_Cash_Management_Activated,
    XVALV AS  Indicator_Propose_Current_Date_As_Value_Date,
    XSKFN AS  Indicator_Discount_Base_Amount_Is_The_Net_Value,
    KKBER AS  Credit_Control_Area,
    XMWSN AS  Indicator_Base_Amount_For_Tax_Is_Net_Of_Discount,
    MREGL AS  Rules_For_Copying_From_The_Sample_Account_For_Gl_Accounts,
    XGSBE AS  Indicator_Business_Area_Financial_Statements_Required,
    XGJRV AS  Indicator_Propose_Fiscal_Year,
    XKDFT AS  Indicator_Post_Translations_For_Exchange_Rate_Differences,
    XPROD AS  Indicator_Productive_Company_Code,
    XEINK AS  Indicator_Purchase_Account_Processing_Is_Active,
    XJVAA AS  Indicator_Jva_Active,
    XVVWA AS  Indicator_Financial_Assets_Management_Active,
    XSLTA AS  Indicator_No_Exrate_Difference_When_Clearing_In_Local_Currency,
    XFDMM AS  Indicator_Updating_Mm_In_Cash_Mgmtforecast_Activated,
    XFDSD AS  Indicator_Updating_Sd_In_Cash_Mgmtforecast_Activated,
    XEXTB AS  Indicator_Company_Code_Is_In_Another_System,
    EBUKR AS  Original_Key_Of_The_Company_Code,
    KTOP2 AS  Chart_Of_Accounts_According_To_Country_Legislation,
    UMKRS AS  Salespurchases_Tax_Group,
    BUKRS_GLOB AS  Name_Of_Global_Company_Code,
    FSTVA AS  Field_Status_Variant,
    OPVAR AS  Posting_Period_Variant,
    XCOVR AS  Indicator_Hedge_Request_Active,
    TXKRS AS  Foreign_Currency_Translation_For_Tax_Items,
    WFVAR AS  Workflow_Variant,
    XBBBF AS  Gl_Account_Authorization_Check_In_Inventory_Management,
    XBBBE AS  Gl_Account_Authorization_Check_In_Poscheduling_Agreement,
    XBBBA AS  Gl_Account_Authorization_Check_In_Purchase_Requisitions,
    XBBKO AS  Gl_Account_Authorization_Check_In_Contracts,
    XSTDT AS  Indicator_Document_Date_As_The_Basis_For_Tax_Determination,
    MWSKV AS  Input_Tax_Code_For_Nontaxable_Transactions,
    MWSKA AS  Output_Tax_Code_For_Nontaxable_Transactions,
    IMPDA AS  Foreign_Trade_Import_Data_Control_In_Mm_Purchase_Orders,
    XNEGP AS  Indicator_Negative_Postings_Permitted,
    XKKBI AS  Indicator_Can_Credit_Control_Area_Be_Overwritten,
    WT_NEWWT AS  Indicator_Extended_Withholding_Tax_Active,
    PP_PDATE AS  Procedure_For_Setting_The_Posting_Date,
    INFMT AS  Inflation_Method,
    FSTVARE AS  Funds_Reservation_Field_Status_Var,
    KOPIM AS  Foreign_Trade_Import_Data_Copying_Control_For_Gr,
    DKWEG AS  Foreign_Trade_Screen_Ctrl_Of_Impdata_F_Mmgoods_Rececipt,
    OFFSACCT AS  Method_For_Offsetting_Account_Determination,
    BAPOVAR AS  Additional_Settings_Variant_For_Busarea_Financial_Statemnts,
    XCOS AS  Cost_Of_Sales_Accounting_Status,
    XCESSION AS  Accounts_Receivable_Pledging_Active,
    XSPLT AS  Enable_Amount_Split,
    SURCCM AS  Surcharge_Calculation_Method,
    DTPROV AS  Document_Type_For_Provisions_For_Taxes_On_Services_Received,
    DTAMTC AS  Document_Type_For_Journal_Voucher_Amount_Correction,
    DTTAXC AS  Document_Type_For_Journal_Voucher_Tax_Code_Correction,
    DTTDSP AS  Document_Type_For_Remittance_Challans,
    DTAXR AS  Deferred_Tax_Rule,
    XVATDATE AS  Tax_Reporting_Date_Active_In_Documents,
    PST_PER_VAR AS  Manage_Variant_Of_Posting_Period_For_Company_Codeledger,
    XBBSC AS  Gl_Account_Authorization_Check_In_Shopping_Cart,
    FM_DERIVE_ACC AS  Activate_Account_Assignment_Derivation_In_Funds_Management,
    ZZSTDXCE AS  Trading_Interface_Corporate_Entity,
    ZZCLASS AS  Partner_Class,
    ZZVKORG AS  Sales_Organization,
    ZZEKORG AS  Purchasing_Organization,
    ZZWERKS AS  Plant,
    ZZSTORU1 AS  1Digit_Abbreviation_For_Organisation,
    ZZSTSTCD AS  Standard_Text_Code_For_A_Company_Code,
    ZZKUNNR AS  Customer_Number,
    ZZTDNAME AS  Text_Name,
    ZZTDNAME2 AS  Text_Name2,
    ZZSEQNO AS  Invoice_Sequence_Number_Required_For_Company_Code,
    ZZTDFLG AS  Title_Transfer_Date_Required_As_Translation_Date_RV60BFZA,
    ZZBLART AS  Document_Type_For_Cancellation_Accounting_Document,
    ZZBLART2 AS  Document_Type_For_Accounting_Document,
    ZZACDOCPR AS  Accounting_Document_No_Printout_On_Invoice_Flag,
    ZZTXKSCHL AS  TAX_Condition_Code_For_Sales,
    ZZTXALTWAERS AS  Alternative_Reporting_Currency_For_Tax,
    ZZSABRIX AS  Element_In_Scope_of_Sabrix,
    F_OBSOLETE AS  Hide_Entry_In_Value_Help,
    ingested_at AS  Ingested_at,
    LAST_DTM AS  LAST_DTM
    from {{ref('T001_STN')}}
    where MANDT='280'
)

select rename_filter_t001_stn.* except(Client, Ingested_at),
current_timestamp() as Ingested_At,
('{{set_system_id()}}'|| "_" || rename_filter_t001_stn.Client) as Source_ID
from rename_filter_t001_stn
