{{
  config(
    materialized = 'incremental',
    unique_key=['Source_ID','Account_Number_Of_Supplier','Company_Code'],
    on_schema_change = 'ignore',
    tags=["MD-EH-SD-D"]
    )
}}

with
rename_filter_lfa1_tsap as (
select
    MANDT AS Client ,
   LIFNR AS Account_Number_Of_Supplier ,
   LAND1 AS Country_Key ,
   NAME1 AS Name_1 ,
   NAME2 AS Name_2 ,
   NAME3 AS Name_3 ,
   NAME4 AS Name_4 ,
   ORT01 AS City ,
   ORT02 AS District ,
   PFACH AS PO_Box ,
   PSTL2 AS PO_Box_Postal_Code ,
   PSTLZ AS Postal_Code ,
   REGIO AS Region_State_Province_County ,
   SORTL AS Sort_Field ,
   STRAS AS Street_And_House_Number ,
   ADRNR AS Address ,
   MCOD1 AS Search_Term_For_Matchcode_Search_1 ,
   MCOD2 AS Search_Term_For_Matchcode_Search_2 ,
   MCOD3 AS Search_Term_For_Matchcode_Search_3 ,
   ANRED AS Title ,
   BAHNS AS Train_Station ,
   BBBNR AS International_Location_Number_Part_1 ,
   BBSNR AS International_Location_Number_Part_2 ,
   BEGRU AS Authorization_Group_LFA1 ,
   BRSCH AS Industry_Key ,
   BUBKZ AS Check_Digit_For_The_International_Location_Number ,
   DATLT AS Data_Communication_Line_No ,
   DTAMS AS Report_Key_For_Data_Medium_Exchange ,
   DTAWS AS Instruction_Key_For_Data_Medium_Exchange ,
   ERDAT AS Date_On_Which_The_Record_Was_Created_LFA1 ,
   ERNAM AS Name_Of_Person_Who_Created_The_Object_LFA1 ,
   ESRNR AS Isr_Subscriber_Number ,
   KONZS AS Group_Key ,
   KTOKK AS Supplier_Account_Group ,
   KUNNR AS Customer_Number ,
   LNRZA AS Account_Number_Of_The_Alternative_Payee_LFA1 ,
   LOEVM AS Central_Deletion_Flag_For_Master_Record ,
   SPERR AS Central_Posting_Block ,
   SPERM AS Centrally_Imposed_Purchasing_Block ,
   SPRAS AS Language_Key ,
   STCD1 AS Tax_Number_1 ,
   STCD2 AS Tax_Number_2 ,
   STKZA AS Indicator_Business_Partner_Subject_To_Equalization_Tax ,
   STKZU AS Liable_For_Vat ,
   TELBX AS Telebox_Number ,
   TELF1 AS First_Telephone_Number ,
   TELF2 AS Second_Telephone_Number ,
   TELFX AS Fax_Number ,
   TELTX AS Teletex_Number ,
   TELX1 AS Telex_Number ,
   XCPDK AS Indicator_Is_The_Account_A_One_Time_Account ,
   XZEMP AS Indicator_Alternative_Payee_In_Document_Allowed ,
   VBUND AS Company_Id_Of_Trading_Partner ,
   FISKN AS Account_Number_Of_The_Master_Record_With_Fiscal_Address ,
   STCEG AS Vat_Registration_Number ,
   STKZN AS Natural_Person ,
   SPERQ AS Function_That_Will_Be_Blocked ,
   GBORT AS Place_Of_Birth_Of_The_Person_Subject_To_Withholding_Tax ,
   GBDAT AS Date_Of_Birth_Of_The_Person_Subject_To_Withholding_Tax ,
   SEXKZ AS Key_For_The_Sex_Of_The_Person_Subject_To_Withholding_Tax ,
   KRAUS AS Credit_Information_Number ,
   REVDB AS Last_Review_External ,
   QSSYS AS Vendors_Qm_System ,
   KTOCK AS Reference_Account_Group_For_One_Time_Account_Vendor ,
   PFORT AS Po_Box_City ,
   WERKS AS Plant_Own_Or_External ,
   LTSNA AS Indicator_Vendor_Sub_Range_Relevant ,
   WERKR AS Indicator_Plant_Level_Relevant ,
   PLKAL AS Factory_Calendar_Key ,
   DUEFL AS Status_Of_Data_Transfer_Into_Subsequent_Release ,
   TXJCD AS Tax_Jurisdiction ,
   SPERZ AS Payment_Block ,
   SCACD AS Standard_Carrier_Access_Code ,
   SFRGR AS Forwarding_Agent_Freight_Group ,
   LZONE AS Transportation_Zone_To_Or_From_Which_The_Goods_Are_Delivered ,
   XLFZA AS Indicator_Alternative_Payee_Using_Account_Number_LFA1 ,
   DLGRP AS Service_Agent_Procedure_Group ,
   FITYP AS Tax_Type ,
   STCDT AS Tax_Number_Type ,
   REGSS AS Registered_For_Social_Insurance ,
   ACTSS AS Activity_Code_For_Social_Insurance ,
   STCD3 AS Tax_Number_3 ,
   STCD4 AS Tax_Number_4 ,
   STCD5 AS Tax_Number_5 ,
   IPISP AS Tax_Split ,
   TAXBS AS Tax_Base_In_Percentage ,
   PROFS AS Profession ,
   STGDL AS Shipment_Statistics_Group_Transportation_Service_Agent ,
   EMNFR AS External_Manufacturer_Code_Name_Or_Number ,
   LFURL AS Uniform_Resource_Locator ,
   J_1KFREPRE AS Name_Of_Representative ,
   J_1KFTBUS AS Type_Of_Business ,
   J_1KFTIND AS Type_Of_Industry ,
   CONFS AS Status_Of_Change_Authorization_Central ,
   UPDAT AS Date_On_Which_The_Changes_Were_Confirmed_LFA1 ,
   UPTIM AS Time_Of_Last_Change_Confirmation_LFA1 ,
   NODEL AS Central_Deletion_Block_For_Master_Record ,
   QSSYSDAT AS Validity_Date_Of_Certification ,
   PODKZB AS Vendor_Indicator_Relevant_For_Proof_Of_Delivery ,
   FISKU AS Account_Number_Of_Master_Record_Of_Tax_Office_Responsible ,
   STENR AS Tax_Number_At_Responsible_Tax_Authority ,
   CARRIER_CONF AS Carrier_Confirmation_Is_Expected ,
   MIN_COMP AS Micro_Company_Indicator ,
   TERM_LI AS Terms_Of_Liability ,
   CRC_NUM AS Crc_Number ,
   CVP_XBLCK AS Business_Purpose_Completed_Flag_LFA1 ,
   RG AS Rg_Number ,
   EXP AS Issued_By ,
   UF AS State ,
   RGDATE AS Rg_Issuing_Date ,
   RIC AS Ric_Number ,
   RNE AS Foreign_National_Registration ,
   RNEDATE AS Rne_Issuing_Date ,
   CNAE AS Cnae ,
   LEGALNAT AS Legal_Nature ,
   CRTN AS Crt_Number ,
   ICMSTAXPAY AS Icms_Taxpayer ,
   INDTYP AS Industry_Main_Type ,
   TDT AS Tax_Declaration_Type ,
   COMSIZE AS Company_Size ,
   DECREGPC AS Declaration_Regimen_For_PisCofins ,
   J_SC_CAPITAL AS Capital_Amount ,
   J_SC_CURRENCY AS Currency ,
   ALC AS Agency_Location_Code ,
   PMT_OFFICE AS Payment_Office ,
   PPA_RELEVANT AS Vendor_Is_Ppa_Relevant ,
   SAM_UE_ID AS System_For_Award_Management_Unique_Entity_Identifier ,
   PSOFG AS Processor_Group ,
   PSOIS AS Subledger_Acct_Preprocessing_Procedure ,
   PSON1 AS Pso_Name_1 ,
   PSON2 AS Pso_Name_2 ,
   PSON3 AS Pso_Name_3 ,
   PSOVN AS First_Name ,
   PSOTL AS Pso_Title ,
   PSOHS AS House_Number_Is_No_Longer_Used_From_Release_46B ,
   PSOST AS Street_No_Longer_Used_From_Release_46B ,
   TRANSPORT_CHAIN AS Transportation_Chain ,
   STAGING_TIME AS Staging_Time_In_Days ,
   SCHEDULING_TYPE AS Scheduling_Procedure ,
   SUBMI_RELEVANT AS Cross_Docking_Relevant_For_Collective_Numbering ,
   LAST_DTM AS LAST_DTM ,
   ingested_at AS ingested_at
  from {{ref('LFA1_TSAP')}}
  where MANDT = '480'
  ),
rename_filter_lfb1_tsap as (
select
  MANDT AS Client ,
   LIFNR AS LFB1_Account_Number_Of_Supplier ,
   BUKRS AS Company_Code ,
   PERNR AS Personnel_Number ,
   SPERR AS Posting_Block_For_Company_Code ,
   LOEVM AS Deletion_Flag_For_Master_Record_Company_Code_Level ,
   ZUAWA AS Key_For_Sorting_According_To_Assignment_Numbers ,
   AKONT AS Reconciliation_Account_In_General_Ledger ,
   VZSKZ AS Interest_Calculation_Indicator ,
   ZWELS AS List_Of_Respected_Payment_Methods ,
   ERDAT AS Date_On_Which_The_Record_Was_Created_LFB1 ,
   ERNAM AS Name_Of_Person_Who_Created_The_Object_LFB1 ,
   XVERR AS Indicator_Clearing_Between_Customer_And_Vendor ,
   ZAHLS AS Block_Key_For_Payment ,
   ZTERM AS Terms_Of_Payment_Key ,
   BEGRU AS Authorization_Group_LFB1 ,
   EIKTO AS Our_Account_Number_With_The_Vendor ,
   ZSABE AS Clerk_At_Vendor ,
   KVERM AS Memo ,
   FDGRV AS Planning_Group ,
   BUSAB AS Accounting_Clerk_Abbreviation ,
   LNRZE AS Head_Office_Account_Number ,
   LNRZB AS Account_Number_Of_The_Alternative_Payee_LFB1 ,
   XLFZB AS Indicator_Alternative_Payee_Using_Account_Number_LFB1 ,
   ZINDT AS Key_Date_Of_Last_Interest_Calculation ,
   ZINRT AS Interest_Calculation_Frequency_In_Months ,
   DATLZ AS Date_Of_The_Last_Interest_Calculation_Run ,
   XDEZV AS Indicator_Local_Processing ,
   WEBTR AS Bill_Of_Exchange_Limit_In_Local_Currency ,
   KULTG AS Probable_Time_Until_Check_Is_Paid ,
   REPRF AS Check_Flag_For_Double_Invoices_Or_Credit_Memos ,
   TOGRU AS Tolerance_Group_For_The_Business_PartnerGL_Account ,
   HBKID AS Short_Key_For_A_House_Bank ,
   XPORE AS Indicator_Pay_All_Items_Separately ,
   QSZNR AS Certificate_Number_Of_The_Withholding_Tax_Exemption ,
   QSZDT AS Validity_Date_For_Withholding_Tax_Exemption_Certificate ,
   QSSKZ AS Withholding_Tax_Code ,
   BLNKZ AS Subsidy_Indicator_For_Determining_The_Reduction_Rates ,
   MINDK AS Minority_Indicators ,
   ALTKN AS Previous_Master_Record_Number ,
   ZGRUP AS Key_For_Payment_Grouping ,
   MGRUP AS Key_For_Dunning_Notice_Grouping ,
   UZAWE AS Payment_Method_Supplement ,
   QSREC AS Vendor_Recipient_Type ,
   QSBGR AS Authority_For_Exemption_From_Withholding_Tax ,
   QLAND AS Withholding_Tax_Country_Key ,
   XEDIP AS Indicator_Send_Payment_Advices_By_Edi ,
   FRGRP AS Release_Approval_Group ,
   TOGRR AS Tolerance_Group_Invoice_Verification ,
   TLFXS AS Accounting_ClerkS_Fax_Number_At_The_CustomerVendor ,
   INTAD AS Internet_Address_Of_Partner_Company_Clerk ,
   GUZTE AS Payment_Terms_Key_For_Credit_Memos ,
   GRICD AS Activity_Code_For_Gross_Income_Tax ,
   GRIDT AS Distribution_Type_For_Employment_Tax ,
   XAUSZ AS Indicator_For_Periodic_Account_Statements ,
   CERDT AS Certification_Date ,
   CONFS AS Status_Of_Change_Authorization_Company_Code_Level ,
   UPDAT AS Date_On_Which_The_Changes_Were_Confirmed_LFB1 ,
   UPTIM AS Time_Of_Last_Change_Confirmation_LFB1 ,
   NODEL AS Deletion_Bock_For_Master_Record_Company_Code_Level ,
   TLFNS AS Accounting_ClerkS_Telephone_Number_At_Business_Partner ,
   AVSND AS Indicator_Send_Payment_Advice_By_Xml ,
   AD_HASH AS E_Mail_Address_For_Avis_Hash_Value ,
   J_SC_SUBCONTYPE AS Subcontractor_Type ,
   J_SC_COMPDATE AS Completion_Date_Of_Inspection ,
   J_SC_OFFSM AS Offset_Method ,
   J_SC_OFFSR AS Offset_Percentage ,
   BASIS_PNT AS Average_Daily_Basis_Points_For_Purchase_Cards ,
   GMVKZK AS Vendor_Is_In_Execution ,
   PREPAY_RELEVANT AS Prepayment_Relevance_Vendor_Master ,
   ASSIGN_TEST AS Assignment_Test_Group ,
   CIIUCODE AS Main_Economic_Activity ,
   ZBOKD AS Ledger_Management_Expiration_Date ,
   CVP_XBLCK_B AS Business_Purpose_Completed_Flag_LFB1 ,
   ZQSSKZ AS Future_Withholding_Tax_Code ,
   ZQSZDT AS Validity_Date_For_Withholding_Tax_Exemption_Certificate_Z ,
   ZQSZNR AS Certificate_Number_Of_The_Withholding_Tax_Exemption_Z ,
   ZMINDAT AS Certification_Date_For_Minimum_Wage ,
   ingested_at AS ingested_at
from {{ref('LFB1_TSAP')}}
where MANDT = '480'
),
lfa1_tsap_delta as (
    select Account_Number_Of_Supplier as Account_Number_Of_Supplier_delta
    from rename_filter_lfa1_tsap
    {% if is_incremental() %}
     where ingested_at > (select max(Ingested_at) from {{this}})
    {% endif %}
),
lfb1_tsap_delta as(
    select LFB1_Account_Number_Of_Supplier
    from rename_filter_lfb1_tsap
    {% if is_incremental() %}
     where ingested_at > (select max(Ingested_at) from {{this}})
    {% endif %}
),
lfa1_lfb1_tsap_pk as(
    select Account_Number_Of_Supplier_delta from lfa1_tsap_delta
    union
    select LFB1_Account_Number_Of_Supplier from lfb1_tsap_delta
),
lfa1_tsap_full(
    select rename_filter_lfa1_tsap.* except (ingested_at)
    from rename_filter_lfa1_tsap
    inner join lfa1_lfb1_tsap_pk
    on rename_filter_lfa1_tsap.Account_Number_Of_Supplier = lfa1_lfb1_tsap_pk.Account_Number_Of_Supplier_delta
),
lfa1_lfb1_tsap_final(
  select lfa1_tsap_full.*,
  rename_filter_lfb1_tsap.* except (Client,LFB1_Account_Number_Of_Supplier,ingested_at)
  from lfa1_tsap_full
  left join rename_filter_lfb1_tsap
  on lfa1_tsap_full.Account_Number_Of_Supplier = rename_filter_lfb1_tsap.LFB1_Account_Number_Of_Supplier
)

select lfa1_lfb1_tsap_final.* except (Client),
current_timestamp() as Ingested_At,
('{{ set_system_id() }}' || "_" || lfa1_lfb1_tsap_final.Client) as Source_ID
from lfa1_lfb1_tsap_final
