{{
  config(
    materialized = 'incremental',
    unique_key=['Source_ID', 'Customer_Number','Company_Code'],
    on_schema_change = 'ignore',
    tags=["MD-EH-SD-D"]
    )
}}

with
rename_filter_kna1_tsap as (

  select
  MANDT AS Client,
KUNNR AS Customer_Number,
LAND1 AS Country_Key,
NAME1 AS Name_1,
NAME2 AS Name_2,
ORT01 AS City,
PSTLZ AS Postal_Code,
REGIO AS Region_State_Province_County,
SORTL AS Sort_Field,
STRAS AS Street_And_House_Number,
TELF1 AS First_Telephone_Number,
TELFX AS Fax_Number,

XCPDK AS Indicator_Is_The_Account_A_One_Time_Account,
ADRNR AS Address,
MCOD1 AS Search_Term_For_Matchcode_Search_1,
MCOD2 AS Search_Term_For_Matchcode_Search_2,
MCOD3 AS Search_Term_For_Matchcode_Search_3,
ANRED AS Title,
AUFSD AS Central_Order_Block_For_Customer,
BAHNE AS Express_Train_Station,
BAHNS AS Train_Station,
BBBNR AS International_Location_Number_Part_1,
BBSNR AS International_Location_Number_Part_2,
BEGRU AS Authorization_Group_KNA1,
BRSCH AS Industry_Key,
BUBKZ AS Check_Digit_For_The_International_Location_Number,
DATLT AS Data_Communication_Line_No,
ERDAT AS Date_On_Which_The_Record_Was_Created_KNA1,
ERNAM AS Name_Of_Person_Who_Created_The_Object_KNA1,
EXABL AS Indicator_Unloading_Points_Exist,
FAKSD AS Central_Billing_Block_For_Customer,
FISKN AS Account_Number_Of_The_Master_Record_With_The_Fiscal_Address,
KNAZK AS Working_Time_Calendar,

KNRZA AS Account_Number_Of_An_Alternative_Payer_KNA1,
KONZS AS Group_Key,
KTOKD AS Customer_Account_Group,
KUKLA AS Customer_Classification,
LIFNR AS Account_Number_Of_Supplier,
LIFSD AS Central_Delivery_Block_For_The_Customer,
LOCCO AS City_Coordinates,
LOEVM AS Central_Deletion_Flag_For_Master_Record,
NAME3 AS Name_3,
NAME4 AS Name_4,
NIELS AS Nielsen_Id,

ORT02 AS District,
PFACH AS Po_Box,
PSTL2 AS PO_Box_Postal_Code,
COUNC AS County_Code,
CITYC AS City_Code,
RPMKR AS Regional_Market,
SPERR AS Central_Posting_Block,
SPRAS AS Language_Key,
STCD1 AS Tax_Number_1,
STCD2 AS Tax_Number_2,
STKZA AS Indicator_Business_Partner_Subject_To_Equalization_Tax,
STKZU AS Liable_For_Vat,

TELBX AS Telebox_Number,
TELF2 AS Second_Telephone_Number,
TELTX AS Teletex_Number,
TELX1 AS Telex_Number,
LZONE AS Transportation_Zone_To_Or_From_Which_The_Goods_Are_Delivered,
XZEMP AS Indicator_Is_An_Alternative_Payer_Allowed_In_Document,
VBUND AS Company_Id_Of_Trading_Partner,
STCEG AS Vat_Registration_Number,
DEAR1 AS Indicator_Competitor,
DEAR2 AS Indicator_Sales_Partner,
DEAR3 AS Indicator_Sales_Prospect,
DEAR4 AS Indicator_For_Customer_Type_4,
DEAR5 AS Id_For_Default_Sold_To_Party,
GFORM AS Legal_Status,
BRAN1 AS Industry_Code_1,
BRAN2 AS Industry_Code_2,
BRAN3 AS Industry_Code_3,
BRAN4 AS Industry_Code_4,
BRAN5 AS Industry_Code_5,
EKONT AS Initial_Contact,
UMSAT AS Annual_Sales,
UMJAH AS Year_For_Which_Sales_Are_Given,
UWAER AS Currency_Of_Sales_Figure,
JMZAH AS Yearly_Number_Of_Employees,
JMJAH AS Year_For_Which_The_Number_Of_Employees_Is_Given,
KATR1 AS Attribute_1,
KATR2 AS Attribute_2,
KATR3 AS Attribute_3,
KATR4 AS Attribute_4,
KATR5 AS Attribute_5,
KATR6 AS Attribute_6,
KATR7 AS Attribute_7,
KATR8 AS Attribute_8,
KATR9 AS Attribute_9,
KATR10 AS Attribute_10,
STKZN AS Natural_Person,
UMSA1 AS Annual_Sales_1,
TXJCD AS Tax_Jurisdiction,
PERIV AS Fiscal_Year_Variant,
ABRVW AS Usage_Indicator,
INSPBYDEBI AS Inspection_Carried_Out_By_Customer_No_Inspection_Lot,
INSPATDEBI AS Inspection_For_A_Delivery_Note_After_Outbound_Delivery,
KTOCD AS Reference_Account_Group_For_One_Time_Account_Customer,
PFORT AS Po_Box_City,
WERKS AS Plant,
DTAMS AS Report_Key_For_Data_Medium_Exchange,
DTAWS AS Instruction_Key_For_Data_Medium_Exchange,
DUEFL AS Status_Of_Data_Transfer_Into_Subsequent_Release,
HZUOR AS Assignment_To_Hierarchy,
SPERZ AS Payment_Block,
ETIKG AS Is_R_Labeling_CustomerPlant_Group,
CIVVE AS Id_For_Mainly_Non_Military_Use,
MILVE AS Id_For_Mainly_Military_Use,
KDKG1 AS Customer_Condition_Group_1,
KDKG2 AS Customer_Condition_Group_2,
KDKG3 AS Customer_Condition_Group_3,
KDKG4 AS Customer_Condition_Group_4,
KDKG5 AS Customer_Condition_Group_5,
XKNZA AS Indicator_Alternative_Payer_Using_Account_Number_KNA1,
FITYP AS Tax_Type,
STCDT AS Tax_Number_Type,
STCD3 AS Tax_Number_3,
STCD4 AS Tax_Number_4,
STCD5 AS Tax_Number_5,
XICMS AS Customer_Is_Icms_Exempt,
XXIPI AS Customer_Is_Ipi_Exempt,
XSUBT AS Customer_Group_For_Substituicao_Tributaria_Calculation,
CFOPC AS Customers_Cfop_Category,
TXLW1 AS Tax_Law_Icms,
TXLW2 AS Tax_Law_Ipi,
CCC01 AS Indicator_For_Biochemical_Warfare_For_Legal_Control,
CCC02 AS Indicator_For_Nuclear_Nonproliferation_For_Legal_Control,
CCC03 AS Indicator_For_National_Security_For_Legal_Control,
CCC04 AS Indicator_For_Missile_Technology_For_Legal_Control,
CASSD AS Central_Sales_Block_For_Customer,
KNURL AS Uniform_Resource_Locator,
J_1KFREPRE AS Name_Of_Representative,
J_1KFTBUS AS Type_Of_Business,
J_1KFTIND AS Type_Of_Industry,
CONFS AS Status_Of_Change_Authorization_Central,
UPDAT AS Date_On_Which_The_Changes_Were_Confirmed_KNA1,
UPTIM AS Time_Of_Last_Change_Confirmation_KNA1,
NODEL AS Central_Deletion_Block_For_Master_Record,
DEAR6 AS Indicator_Consumer,
CVP_XBLCK AS Business_Purpose_Completed_Flag_KNA1,
SUFRAMA AS Suframa_Code,
RG AS Rg_Number,
EXP AS Issued_By,
UF AS State,
RGDATE AS Rg_Issuing_Date,
RIC AS Ric_Number,
RNE AS Foreign_National_Registration,
RNEDATE AS Rne_Issuing_Date,
CNAE AS Cnae,
LEGALNAT AS Legal_Nature,
CRTN AS Crt_Number,
ICMSTAXPAY AS Icms_Taxpayer,
INDTYP AS Industry_Main_Type,
TDT AS Tax_Declaration_Type,
COMSIZE AS Company_Size,

DECREGPC AS Declaration_Regimen_For_PisCofins,
`/VSO/R_PALHGT` AS Maximum_Stacking_Height_Of_The_Packaging_Material_Vso,
`/VSO/R_PAL_UL` AS Unit_Of_Length_For_Packaging_Material_Vso,
`/VSO/R_PK_MAT` AS Customer_Related_Packing_For_Each_Packaging_Material_Vso,
`/VSO/R_MATPAL` AS Packaging_Material_Of_The_Customer_In_Vso,
`/VSO/R_I_NO_LYR` AS Number_Layers_Under_An_Inter_Pallet_Vso,
`/VSO/R_ONE_MAT` AS Packing_Material_Specific_For_Each_Packaging_Material,
`/VSO/R_ONE_SORT` AS Pack_Only_One_Package_Type_For_Each_Pkm_Vso,
`/VSO/R_ULD_SIDE` AS Side_Preference_Of_LoadingUnloading_Vso,
`/VSO/R_LOAD_PREF` AS FrontBack_Preference_Of_LoadingUnloading_Vso,
`/VSO/R_DPOINT` AS Collective_Unloading_Point_For_Vso,
ALC AS Agency_Location_Code,
PMT_OFFICE AS Payment_Office,
FEE_SCHEDULE AS Fee_Schedule,
DUNS AS Duns_Number,
DUNS4 AS Duns_4,
SAM_UE_ID AS System_For_Award_Management_Unique_Entity_Identifier,
SAM_EFT_IND AS System_For_Aware_Management_Electronic_Funds_Transfer_Ind,
PSOFG AS Processor_Group,
PSOIS AS Subledger_Acct_Preprocessing_Procedure,
PSON1 AS Pso_Name_1,
PSON2 AS Pso_Name_2,
PSON3 AS Pso_Name_3,

PSOVN AS First_Name,
PSOTL AS Pso_Title,
PSOHS AS House_Number_Is_No_Longer_Used_From_Release_46B,
PSOST AS Street_No_Longer_Used_From_Release_46B,
PSOO1 AS Description_1,
PSOO2 AS Description_2,
PSOO3 AS Description_3,
PSOO4 AS Description_4,
PSOO5 AS Description_5,
LAST_DTM AS LAST_DTM,
ingested_at AS Ingested_at
from {{ref('KNA1_TSAP')}}
where MANDT ='480'
),



rename_filter_knb1_tsap as (
  select
  MANDT AS Client,
KUNNR AS KNB1_Customer_Number,
BUKRS AS Company_Code,
PERNR AS Personnel_Number,
ERDAT AS Date_On_Which_The_Record_Was_Created_KNB1,
ERNAM AS Name_Of_Person_Who_Created_The_Object_KNB1,

SPERR AS Posting_Block_For_Company_Code,
LOEVM AS Deletion_Flag_For_Master_Record_Company_Code_Level,
ZUAWA AS Key_For_Sorting_According_To_Assignment_Numbers,
BUSAB AS Accounting_Clerk_Abbreviation,
AKONT AS Reconciliation_Account_In_General_Ledger,
BEGRU AS Authorization_Group_KNB1,
KNRZE AS Head_Office_Account_Number_In_Branch_Accounts,
KNRZB AS Account_Number_Of_An_Alternative_Payer_KNB1,
ZAMIM AS Indicator_Payment_Notice_To_Customer_With_Cleared_Items,
ZAMIV AS Indicator_Payment_Notice_To_Sales_Department,
ZAMIR AS Indicator_Payment_Notice_To_Legal_Department,
ZAMIB AS Indicator_Payment_Notice_To_The_Accounting_Department,
ZAMIO AS Indicator_Payment_Notice_To_Customer_WO_Cleared_Items,
ZWELS AS List_Of_Respected_Payment_Methods,
XVERR AS Indicator_Clearing_Between_Customer_And_Vendor,
ZAHLS AS Block_Key_For_Payment,
ZTERM AS Terms_Of_Payment_Key,
WAKON AS Terms_Of_Payment_Key_For_Bill_Of_Exchange_Charges,
VZSKZ AS Interest_Calculation_Indicator,
ZINDT AS Key_Date_Of_Last_Interest_Calculation,
ZINRT AS Interest_Calculation_Frequency_In_Months,
EIKTO AS Our_Account_Number_At_Customer,
ZSABE AS User_At_Customer,
KVERM AS Memo,
FDGRV AS Planning_Group,
VRBKZ AS Export_Credit_Insurance_Institution_Number,
VLIBB AS Amount_Insured,
VRSZL AS Insurance_Lead_Months,
VRSPR AS Deductible_Percentage_Rate,
VRSNR AS Insurance_Number,
VERDT AS Insurance_Validity_Date,
PERKZ AS Collective_Invoice_Variant,
XDEZV AS Indicator_Local_Processing,
XAUSZ AS Indicator_For_Periodic_Account_Statements,
WEBTR AS Bill_Of_Exchange_Limit_In_Local_Currency,
REMIT AS Next_Payee,
DATLZ AS Date_Of_The_Last_Interest_Calculation_Run,
XZVER AS Indicator_Record_Payment_History,
TOGRU AS Tolerance_Group_For_The_Business_PartnerGL_Account,
KULTG AS Probable_Time_Until_Check_Is_Paid,
HBKID AS Short_Key_For_A_House_Bank,
XPORE AS Indicator_Pay_All_Items_Separately,
BLNKZ AS Subsidy_Indicator_For_Determining_The_Reduction_Rates,
ALTKN AS Previous_Master_Record_Number,
ZGRUP AS Key_For_Payment_Grouping,
URLID AS Short_Key_For_KnownNegotiated_Leave,
MGRUP AS Key_For_Dunning_Notice_Grouping,
LOCKB AS Key_Of_The_Lockbox_To_Which_The_Customer_Is_To_Pay,
UZAWE AS Payment_Method_Supplement,
EKVBD AS Account_Number_Of_Buying_Group,
SREGL AS Selection_Rule_For_Payment_Advices,
XEDIP AS Indicator_Send_Payment_Advices_By_Edi,
FRGRP AS Release_Approval_Group,
VRSDG AS Reason_Code_Conversion_Version,
TLFXS AS Accounting_ClerkS_Fax_Number_At_The_CustomerVendor,
INTAD AS Internet_Address_Of_Partner_Company_Clerk,
XKNZB AS Indicator_Alternative_Payer_Using_Account_Number_KNB1,
GUZTE AS Payment_Terms_Key_For_Credit_Memos,

GRICD AS Activity_Code_For_Gross_Income_Tax,
GRIDT AS Distribution_Type_For_Employment_Tax,
WBRSL AS Value_Adjustment_Key,
CONFS AS Status_Of_Change_Authorization_Company_Code_Level,
UPDAT AS Date_On_Which_The_Changes_Were_Confirmed_KNB1,
UPTIM AS Time_Of_Last_Change_Confirmation_KNB1,
NODEL AS Deletion_Bock_For_Master_Record_Company_Code_Level,
TLFNS AS Accounting_ClerkS_Telephone_Number_At_Business_Partner,
CESSION_KZ AS Accounts_Receivable_Pledging_Indicator,
AVSND AS Indicator_Send_Payment_Advice_By_Xml,
AD_HASH AS E_Mail_Address_For_Avis_Hash_Value,
QLAND AS Withholding_Tax_Country_Key,
CVP_XBLCK_B AS Business_Purpose_Completed_Flag_KNB1,
CIIUCODE AS Main_Economic_Activity,
GMVKZD AS Customer_Is_In_Execution,
ingested_at AS Ingested_at
from {{ref('KNB1_TSAP')}}
where MANDT = '580'
),

kna1_tsap_delta as (
  select Customer_Number as Customer_Number_delta
  from rename_filter_kna1_tsap
  {% if is_incremental() %}
    where ingested_at > (select max(Ingested_at) from {{this}})
  {% endif %}
),

knb1_tsap_delta as (
  select KNB1_Customer_Number from rename_filter_knb1_tsap
  {% if is_incremental() %}
    where ingested_at>(select max(Ingested_at) from {{this}})
  {% endif %}
),

kna1_knb1_tsap_pk as(
  select Customer_Number_delta from kna1_tsap_delta
  union
  select KNB1_Customer_Number from knb1_tsap_delta
),

kna1_tsap_full(
  select rename_filter_kna1_tsap.* except(ingested_at) from rename_filter_kna1_tsap inner join kna1_knb1_tsap_pk on
  rename_filter_kna1_tsap.Customer_Number=kna1_knb1_tsap_pk.Customer_Number_delta

),

kna1_knb1_tsap_final(
  select kna1_tsap_full.*,
  rename_filter_knb1_tsap.* except (Client, KNB1_Customer_Number,ingested_at)
  from kna1_tsap_full
  left join rename_filter_knb1_tsap
  on kna1_tsap_full.Customer_Number=rename_filter_knb1_tsap.KNB1_Customer_Number
)

select kna1_knb1_tsap_final.* except(Client),
current_timestamp() as Ingested_At,
('{{set_system_id()}}' || "_"|| kna1_knb1_tsap_final.Client) as Source_ID
from kna1_knb1_tsap_final
