{{
  config(
    materialized = 'incremental',
    unique_key=['MANDT', 'VBELN'],
    on_schema_change = 'ignore',
    partition_by=['partition_key'],
    post_hook="DELETE FROM {{ this }} WHERE OPFLAG = 'D'",
    tags=["SD-EUH-D"]
    )
}}

with
source as (
    select MANDT, VBELN, ERDAT, ERZET, ERNAM, ANGDT, BNDDT, AUDAT, VBTYP, TRVOG, AUART, AUGRU,
    GWLDT, SUBMI, LIFSK, FAKSK, NETWR, WAERK, VKORG, VTWEG, SPART, VKGRP, VKBUR, GSBER, GSKST,
    GUEBG, GUEEN, KNUMV, VDATU, VPRGR, AUTLF, VBKLA, VBKLT, KALSM, VSBED, FKARA, AWAHR, KTEXT,
    BSTNK, BSARK, BSTDK, BSTZD, IHREZ, BNAME, TELF1, MAHZA, MAHDT, KUNNR, KOSTL, STAFO, STWAE,
    AEDAT, KVGR1, KVGR2, KVGR3, KVGR4, KVGR5, KNUMA, KOKRS, PS_PSP_PNR, KURST, KKBER, KNKLI,
    GRUPP, SBGRP, CTLPC, CMWAE, CMFRE, CMNUP, CMNGV, AMTBL, HITYP_PR, ABRVW, ABDIS, VGBEL,
    OBJNR, BUKRS_VF, TAXK1, TAXK2, TAXK3, TAXK4, TAXK5, TAXK6, TAXK7, TAXK8, TAXK9, XBLNR,
    ZUONR, VGTYP, KALSM_CH, AGRZR, AUFNR, QMNUM, VBELN_GRP, SCHEME_GRP, ABRUF_PART, ABHOD,
    ABHOV, ABHOB, RPLNR, VZEIT, STCEG_L, LANDTX, XEGDR, ENQUEUE_GRP, DAT_FZAU, FMBDAT,
    VSNMR_V, HANDLE, PROLI, CONT_DG, CRM_GUID, UPD_TMSTMP, MSR_ID, TM_CTRL_KEY,
    HANDOVERLOC, ZREL_DATE, ZREL_TIME, ZSTI_SCTIND, ZSTI_IND, ZIATA, ZICAO, ZCTYPE,
    ZEUSE, ZNDEST, ZSHMIS, ZFREPO, ZREFNO, ZREGNO, ZTRTYP, ZSTTIM, ZENTIM, Z_CUTOFF_DATE,
    Z_CUTOFF_TIME, Z_TIMEZONE, PSM_BUDAT, SWENR, SMENR, PHASE, MTLAUR, STAGE, HB_CONT_REASON,
    HB_EXPDATE, HB_RESDATE, OID_EXTBOL, OID_MISCDL, OIDMSG_SHP, OIDSTS_SHP, OIPIPEVAL, OIC_LIFNR,
    OIC_DCITYC, OIC_DCOUNC, OIC_DREGIO, OIC_DLAND1, OIC_OCITYC, OIC_OCOUNC, OIC_OREGIO, OIC_OLAND1,
    OIC_PORGIN, OIC_PDESTN, OIC_PTRIP, OIC_PBATCH, OIC_MOT, OIC_AORGIN, OIC_ADESTN, OIC_TRUCKN,
    OIA_BASELO, OIINEX, OIISOIL, OIPTRFNC, OIPARTNR, OILASTOR, OIDRC, OIEXGNUM, OIEXGTYP,
    OICHEADOFF, OIPBL, OIDRESTR, OIDMSG_PRD, OIDMSG_QTY, OIDMSG_UOM, OIDMSG_DAT, OIDMSG_TRM,
    OICNTPER, OICNTNTE, OICNTPHO, OID_SORTL, OID_SORT2, OICFKARTDI, OIAEVGTYPE, OIU_CT_TYPE_CD,
    OIU_CUST_VEND_CD, OIU_APPR_FL, OIU_APPR_DT, OIU_EXEC_DT, OIU_STD_CT_FL, OIU_PREV_CT_NO,
    OIU_GPLT_COMPANY, OIU_GPLT_VNAME, OIU_GPLT_DOI_NO, OIU_MK_REP_NO, OIU_MK_REP_ISQ,
    OIU_DEST_SALE_CD, OIU_LIFE_LSE_FL, OIU_INV_NO, OIU_INV_FL, OIU_OBLIG_DT, OIU_DESK_CD,
    OIU_EIA_GINA_CD, OIU_CT_STATUS_CD, OIU_SPOT_TERM_CD, OIU_STNDEDQ_CD, OIU_IOTR_FL,
    OIU_INTRA_INTER, OIU_EXRES_SPLT, OIU_EVGN_FL, OIU_EVGNPD_BAS, OIU_EVGN_PERD_QY,
    OIU_PREIM_TM_CD, OIU_PRIM_TM_QY, OIU_SEC_TM_CD, OIU_SEC_TM_QY, OIU_EXP_NOTIF_DT,
    OIU_INTIT_RDT_DT, OIU_NEXT_RDT_DT, OIU_RTC_DT, OIU_RDT_N_PERD, OIU_RDT_REFQ_CD, OIU_RTF_CD,
    OIU_IMB_PRVSN_FL, OIU_FFEE_RMB_FL, OIU_FIRM_INTRPT, OIU_BAL_BAS_CD, OIU_PNTY_BAS_CD,
    OIU_TRANSP_BA, OIU_DLY_MAX_T_QY, OIU_PRCS_FL, OIU_SPR_FL, OIU_DEHYD_FL, OIU_COMPR_FL,
    OIU_PYMT_METH_CD, OIU_CON_MATNR, OIU_CON_MAX_QY, OIU_AFFIL_FL, OIU_MMS_TYPE_CD,
    OIU_MMS_ETPAY_FL, OIUH_CT_NO, LOGSYSB, KALCD, MULTI, SPPAYM, _DATAAGING, GLO_LOG_REF1_HD,
    FSH_KVGR6, FSH_KVGR7, FSH_KVGR8, FSH_KVGR9, FSH_KVGR10, FSH_REREG, FSH_CQ_CHECK,
    FSH_VRSN_STATUS, FSH_TRANSACTION, FSH_VAS_CG, FSH_CANDATE, FSH_SS, FSH_OS_STG_CHANGE,
    MILL_APPL_ID, TAS, BETC, MOD_ALLOW, CANCEL_ALLOW, PAY_METHOD, BPN, REP_FREQ, WTYSC_CLM_HDR,
    ingested_at, LAST_ACTION_CD, LAST_DTM, SYSTEM_ID, ZPRD_ORD_TYP_ID, ZVBELN_ID, ZCUR_ID, ZCUS_SLD_TO_ID, ZAUGRU_ID, ZSALES_ORG_ID,
   "HANA" as _dbt_source_relation, '' as AESID, '' as AERUNID, '' as AEDATTM, '' as OPFLAG, '' as AERECNO, RIGHT(VBELN,{{var("partition_var")}}) AS partition_key
    from {{ source('raw-ds-dbt','VBAK') }}
    union
    select MANDT, VBELN, ERDAT, ERZET, ERNAM, ANGDT, BNDDT, AUDAT, VBTYP, TRVOG, AUART, AUGRU,
    GWLDT, SUBMI, LIFSK, FAKSK, NETWR, WAERK, VKORG, VTWEG, SPART, VKGRP, VKBUR, GSBER, GSKST,
    GUEBG, GUEEN, KNUMV, VDATU, VPRGR, AUTLF, VBKLA, VBKLT, KALSM, VSBED, FKARA, AWAHR, KTEXT,
    BSTNK, BSARK, BSTDK, BSTZD, IHREZ, BNAME, TELF1, MAHZA, MAHDT, KUNNR, KOSTL, STAFO, STWAE,
    AEDAT, KVGR1, KVGR2, KVGR3, KVGR4, KVGR5, KNUMA, KOKRS, PS_PSP_PNR, KURST, KKBER, KNKLI,
    GRUPP, SBGRP, CTLPC, CMWAE, CMFRE, CMNUP, CMNGV, AMTBL, HITYP_PR, ABRVW, ABDIS, VGBEL,
    OBJNR, BUKRS_VF, TAXK1, TAXK2, TAXK3, TAXK4, TAXK5, TAXK6, TAXK7, TAXK8, TAXK9, XBLNR,
    ZUONR, VGTYP, KALSM_CH, AGRZR, AUFNR, QMNUM, VBELN_GRP, SCHEME_GRP, ABRUF_PART, ABHOD,
    ABHOV, ABHOB, RPLNR, VZEIT, STCEG_L, LANDTX, XEGDR, ENQUEUE_GRP, DAT_FZAU, FMBDAT,
    VSNMR_V, HANDLE, PROLI, CONT_DG, CRM_GUID, UPD_TMSTMP, MSR_ID, TM_CTRL_KEY,
    HANDOVERLOC, ZREL_DATE, ZREL_TIME, ZSTI_SCTIND, ZSTI_IND, ZIATA, ZICAO, ZCTYPE,
    ZEUSE, ZNDEST, ZSHMIS, ZFREPO, ZREFNO, ZREGNO, ZTRTYP, ZSTTIM, ZENTIM, Z_CUTOFF_DATE,
    Z_CUTOFF_TIME, Z_TIMEZONE, PSM_BUDAT, SWENR, SMENR, PHASE, MTLAUR, STAGE, HB_CONT_REASON,
    HB_EXPDATE, HB_RESDATE, OID_EXTBOL, OID_MISCDL, OIDMSG_SHP, OIDSTS_SHP, OIPIPEVAL, OIC_LIFNR,
    OIC_DCITYC, OIC_DCOUNC, OIC_DREGIO, OIC_DLAND1, OIC_OCITYC, OIC_OCOUNC, OIC_OREGIO, OIC_OLAND1,
    OIC_PORGIN, OIC_PDESTN, OIC_PTRIP, OIC_PBATCH, OIC_MOT, OIC_AORGIN, OIC_ADESTN, OIC_TRUCKN,
    OIA_BASELO, OIINEX, OIISOIL, OIPTRFNC, OIPARTNR, OILASTOR, OIDRC, OIEXGNUM, OIEXGTYP,
    OICHEADOFF, OIPBL, OIDRESTR, OIDMSG_PRD, OIDMSG_QTY, OIDMSG_UOM, OIDMSG_DAT, OIDMSG_TRM,
    OICNTPER, OICNTNTE, OICNTPHO, OID_SORTL, OID_SORT2, OICFKARTDI, OIAEVGTYPE, OIU_CT_TYPE_CD,
    OIU_CUST_VEND_CD, OIU_APPR_FL, OIU_APPR_DT, OIU_EXEC_DT, OIU_STD_CT_FL, OIU_PREV_CT_NO,
    OIU_GPLT_COMPANY, OIU_GPLT_VNAME, OIU_GPLT_DOI_NO, OIU_MK_REP_NO, OIU_MK_REP_ISQ,
    OIU_DEST_SALE_CD, OIU_LIFE_LSE_FL, OIU_INV_NO, OIU_INV_FL, OIU_OBLIG_DT, OIU_DESK_CD,
    OIU_EIA_GINA_CD, OIU_CT_STATUS_CD, OIU_SPOT_TERM_CD, OIU_STNDEDQ_CD, OIU_IOTR_FL,
    OIU_INTRA_INTER, OIU_EXRES_SPLT, OIU_EVGN_FL, OIU_EVGNPD_BAS, OIU_EVGN_PERD_QY,
    OIU_PREIM_TM_CD, OIU_PRIM_TM_QY, OIU_SEC_TM_CD, OIU_SEC_TM_QY, OIU_EXP_NOTIF_DT,
    OIU_INTIT_RDT_DT, OIU_NEXT_RDT_DT, OIU_RTC_DT, OIU_RDT_N_PERD, OIU_RDT_REFQ_CD, OIU_RTF_CD,
    OIU_IMB_PRVSN_FL, OIU_FFEE_RMB_FL, OIU_FIRM_INTRPT, OIU_BAL_BAS_CD, OIU_PNTY_BAS_CD,
    OIU_TRANSP_BA, OIU_DLY_MAX_T_QY, OIU_PRCS_FL, OIU_SPR_FL, OIU_DEHYD_FL, OIU_COMPR_FL,
    OIU_PYMT_METH_CD, OIU_CON_MATNR, OIU_CON_MAX_QY, OIU_AFFIL_FL, OIU_MMS_TYPE_CD,
    OIU_MMS_ETPAY_FL, OIUH_CT_NO, LOGSYSB, KALCD, MULTI, SPPAYM, _DATAAGING, GLO_LOG_REF1_HD,
    FSH_KVGR6, FSH_KVGR7, FSH_KVGR8, FSH_KVGR9, FSH_KVGR10, FSH_REREG, FSH_CQ_CHECK,
    FSH_VRSN_STATUS, FSH_TRANSACTION, FSH_VAS_CG, FSH_CANDATE, FSH_SS, FSH_OS_STG_CHANGE,
    MILL_APPL_ID, TAS, BETC, MOD_ALLOW, CANCEL_ALLOW, PAY_METHOD, BPN, REP_FREQ, WTYSC_CLM_HDR,
    ingested_at,  '' as LAST_ACTION_CD, '' as LAST_DTM, '' as SYSTEM_ID, '' as  ZPRD_ORD_TYP_ID,
    '' as  ZVBELN_ID, '' as  ZCUR_ID, '' as  ZCUS_SLD_TO_ID, '' as  ZAUGRU_ID,
    '' as  ZSALES_ORG_ID, "AECORSOFT" AS _dbt_source_relation, AESID, AERUNID, AEDATTM, OPFLAG,
    AERECNO, RIGHT(VBELN,{{var("partition_var")}}) AS partition_key
    from {{ source('raw-ds-dbt','AECORSOFT_VBAK')}}
    where AEDATTM is not null
)

select *
from source
